name: Run Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install '.[testing]'
      - name: Run mypy
        run: |
          mypy ./web-browser-export
      - name: Run pytest
        run: |
          pytest
      - name: Run flake8
        run: |
          flake8 ./web-browser-export
